/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    application
    id("buildlogic.java-application-conventions")
    id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {
    mavenCentral()
}

javafx {
    version = "21"
    modules("javafx.controls", "javafx.fxml")
}

dependencies {
    implementation(project(":common"))
    implementation("org.apache.commons:commons-text")
    implementation("org.postgresql:postgresql:42.7.7")
    implementation("org.openjfx:javafx-controls:21")
    implementation("org.openjfx:javafx-fxml:21")
    implementation("org.openjfx:javafx-base:21")
    implementation("org.openjfx:javafx-graphics:21")
    testImplementation("junit:junit:4.13.2")
}

application {
    // Define the main class for the application.
    mainClass = "koolfileindexer.App"
    applicationDefaultJvmArgs =
        listOf(
            "--add-modules=javafx.controls,javafx.fxml",
        )
}
